---
title: "Bayesian (Generalized) Linear Models"
subtitle: "Outline"
author: "Lona Koers"
output: pdf_document
---

0. Abstract

1. Introduction

    - Motivation of bayesian GLMs: uncertainty quantification, regularization, incorporation of domain knowledge, small data sets
    - Current research and related work
    - Structure of the paper


2. Bayesian Linear Regression

    2.1 Model definition
      - Regular linear model
      - Bayesian linear model

    2.2 Prior choice
      - Uninformative priors (for $\beta$ and $\sigma^2$ or just for $\sigma^2$)
      - Prior distributions for regularization
          - Motivation of regularization
          - Ridge regularization $\iff$ Gaussian prior
          - Focus: Lasso regularization $\iff$ Laplace prior (and other methodes for real variable selection)
      - Other prior distributions and use-cases (i.e. heavy-tailed priors) (?)
    
    2.3 Bayesian inference with closed form priors
      - Posterior and marginal (parameter) distribution
      - Posterior predictive distribution
  
    2.5 Model evaluation (?)


3. Bayesian Generalised Linear Regression

    3.1 Extending linear regression *(alternative: last subchapter after logistic regression)*
      - Bayesian GLMs for any exponential family distribution

    3.2 (Binary) Logistic regression
      - Model definition
      - Parameter priors

    3.3. Inference methods
      - Laplace approximation
      - MCMC and Hamilton Monte Carlo
    
    3.4 Predictive posterior
      - Predictive posterior estimation
      - Model checking (?)


4. Simulation Study

    4.1. Linear Regression (= Regression): prior choice for bayesian linear regression with (Lasso) regularization

    4.2. Logistic Regression (= Classification)
      <!-- - synthetic data (easy 2-dim binary classification where we can draw a line through? maybe effect on the decision boundary with unbalanced classes is interesting?) -->
      <!-- - fit model -->
      <!-- - visualize prior, posterior, predictive posterior, posterior decision boundary -->

5. Discussion

    - When would the use of Bayesian regression be preferred over regular regression?
    - Alternatives for more complex problems: Hierarchical GLMs and GLMMs
    - Are there Bayesian GAMs?

6. Conclusion and Outlook

